name: graphs # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.5.1' # just for humans, typically '1.2+git' or '1.3.2'
icon: se.sjoerd.Graphs.svg
adopt-info: graphs
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
license: GPL-3.0
parts:
  graphs:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/Sjoerd1993/Graphs.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/snap/graphs/current/usr
    build-packages:
      - blueprint-compiler
    override-build: |
      craftctl default
      pip install --target=$CRAFT_PART_INSTALL/snap/graphs/current/usr/lib/python3/dist-packages matplotlib
      pip install --target=$CRAFT_PART_INSTALL/snap/graphs/current/usr/lib/python3/dist-packages scipy
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/graphs/current/usr/bin/graphs"
    organize:
      snap/graphs/current/usr: usr
    parse-info: [usr/share/appdata/se.sjoerd.Graphs.appdata.xml]
    
apps:
  graphs:
    command: usr/bin/graphs
    desktop: usr/share/applications/se.sjoerd.Graphs.desktop
    common-id: se.sjoerd.Graphs
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/share/graphs:$PYTHONPATH
    extensions: [gnome]
